"""
Write the Windows VS_VERSIONINFO resource that PyInstaller stamps onto the exe.

Without it the built executable shows no publisher or version in its file
properties, which looks like unattributed software to both users and antivirus
heuristics. Generated from version.py so there is one source of truth.

Usage:  python packaging/make_version_file.py
Writes: packaging/file_version_info.txt
"""

import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, ROOT)

from version import APP_ID, APP_NAME, PUBLISHER, __version__  # noqa: E402

parts = [int(p) for p in __version__.split(".")]
while len(parts) < 4:
    parts.append(0)
vers = tuple(parts[:4])

TEMPLATE = """# Generated by packaging/make_version_file.py - do not edit by hand.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={vers},
    prodvers={vers},
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo([
      StringTable(
        '040904B0',
        [StringStruct('CompanyName', '{publisher}'),
         StringStruct('FileDescription', '{app_name}'),
         StringStruct('FileVersion', '{version}'),
         StringStruct('InternalName', '{app_id}'),
         StringStruct('LegalCopyright', 'Copyright (C) 2025 {publisher}. All Rights Reserved.'),
         StringStruct('OriginalFilename', '{app_id}.exe'),
         StringStruct('ProductName', '{app_name}'),
         StringStruct('ProductVersion', '{version}')])
    ]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])])
  ]
)
"""

out = os.path.join(HERE, "file_version_info.txt")
with open(out, "w", encoding="utf-8") as fh:
    fh.write(TEMPLATE.format(vers=vers, version=__version__, app_name=APP_NAME,
                             app_id=APP_ID, publisher=PUBLISHER))
print(f"wrote {out} for version {__version__}")
